query gameRandomFactsVoteByPlayerIdAndRoundId(
  $playerId: Int!
  $roundId: Int!
) {
  gameRandomFactsVoteByPlayerIdAndRoundId(
    playerId: $playerId
    roundId: $roundId
  ) {
    ...GameRandomFactsVoteItem
  }
}
