query playerByInvitationCodeFn($invitationCode: UUID!) {
  playerByInvitationCodeFn(invitationCode: $invitationCode) {
    nodes {
      id
      name
      teamByTeamId {
        id
        name
        emoji
        charityOrganizationByCharityOrganizationId {
          id
          name
          url
        }
        donationUrl
        eventByEventId {
          id
          name
          start
          end
          discordInviteCode
          streamUrl
          commonDonationUrl
        }
      }
    }
  }
}
